### PR TITLE
Add TruffleRuby to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by gogainda** [comment]
@eregon @kou truffleruby works on ubuntu and macos (windows is not supported I guess) but we have other runs which are failing here. Should I clean up the matrix and mark the failing runs as allow_failures?

**Comment by eregon** [comment]
Yes, please exclude the truffleruby + Windows jobs like done here:
https://github.com/ruby/setup-ruby/blob/ad2d64d83c735b71d92496bb0a0ab9b41b1b06b1/.github/workflows/test.yml#L32
TruffleRuby does not support Windows currently.

**Comment by gogainda** [comment]
@kou truffleruby works fine, feel free to review/merge

**Comment by kou** [comment]
Thanks!

**Pull request merged**
